package: demo_base
version: '1.2'
author: Peter Bickel, Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'Basis-Demo'
    pjax: true
    subpages:
        description: { title: 'Basis-Demo' }

requires:
    packages:
        backup: '>=2.0.2'
        structure/content: '>=2.0.1'
        textile: '>=2.0.0'
        rex_redactor: '>=1.6.1'
        rex_markitup: '>=1.4.0'
        yform: '>=1.0-beta4'
        phpmailer: '>=2.0.1'
    redaxo: '>=5.1.0'
