package: demo_base
version: 2.6.0
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_base'

page:
    title: Basis-Demo
    perm: 'demo_base[]'
    pjax: true
    subpages:
        install: { title: 'translate:title' }

requires:
    packages:
        backup: '>=2.0.4'
        structure/content: '>=2.3.1'
    redaxo: '>=5.3.0'
