package: demo_base
version: '2.2.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/demo_base

page:
    title: 'Basis-Demo'
    perm: demo_base[]
    pjax: true
    subpages:
        description: { title: 'Basis-Demo' }

requires:
    packages:
        backup: '>=2.0.3'
        structure/content: '>=2.1.0'
        markitup: '>=3.0.0'
        redactor2: '>=3.0.0'
        yform: '>=2.0.0'
        phpmailer: '>=2.1.0'
        sprog: '>=1.0.0-beta4'
    redaxo: '>=5.2.0'
