package: demo_base
version: 2.6.2
author: 'Friends Of REDAXO'
supportpage: 'https://github.com/FriendsOfREDAXO/demo_base'
page:
    title: Basis-Demo
    perm: 'demo_base[]'
    pjax: true
    subpages:
        install: { title: 'translate:title' }
requires:
    packages:
        backup: '>=2.2.2'
        structure/content: '>=2.6.0'
        markitup: '>=3.2.0'
        phpmailer: '>=2.1.2'
        redactor2: '>=3.5.0'
        sprog: '>=1.1.0'
        yform: '>=3.0-beta2'
    redaxo: '>=5.6.4'
setup:
    packages:
        markitup: 2588
        phpmailer: 1821
        redactor2: 2514
        sprog: 1446
        yform: 2538
    installSequence:
        - backup
        - structure/content
        - phpmailer
        - markitup
        - redactor2
        - sprog
        - yform
    dbimport:
        - demo_base.sql
    fileimport:
        - demo_base.tar.gz
