package: demo_base
version: '1.2'
author: Peter Bickel, Thomas Blum
supportpage: www.redaxo.org/de/forum/

page:
    title: 'Basis-Demo'
    pjax: true
    subpages:
        description: { title: 'Basis-Demo' }

requires:
    packages:
        backup: '>=2.0.3'
        structure/content: '>=2.1.0'
        textile: '>=2.0.0'
        rex_redactor: '>=1.6.3'
        rex_markitup: '>=1.4.2'
        slice_ui: '>= 2.3.2'
        yform: '>=1.0-beta7'
        phpmailer: '>=2.1.0'
    redaxo: '>=5.1.0'
